service: language-learning-api
frameworkVersion: '3'

custom:
  authorizer:
    arn: ${file(./config/config.json):userPoolArn}

provider:
  name: aws
  runtime: nodejs14.x

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "translate:TranslateText"
            - "translate:ListLanguages"
          Resource:
            - "*"

functions:
  translate:
    handler: src/controller/translate/handler.translate
    events:
      - http:
          path: translate
          method: post
          authorizer: ${self:custom.authorizer}
          cors: true
  getSupportedLanguages:
    handler: src/controller/getSupportedLanguages/handler.getSupportedLanguages
    events:
      - http:
          path: supportedLanguages
          method: get
          authorizer: ${self:custom.authorizer}
          cors: true

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'

plugins:
  - serverless-offline
  - serverless-plugin-typescript
