service: language-learning-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello:
    handler: src/controller/translate/handler.translate
    events:
      - http:
          path: translate
          method: post

plugins:
  - serverless-esbuild
  - serverless-offline
