service: language-learning-api
frameworkVersion: '3'

custom:
  authorizer:
    arn: ${file(./config/config.json):userPoolArn}

provider:
  name: aws
  runtime: nodejs14.x

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "translate:TranslateText"
          Resource:
            - "*"

functions:
  translate:
    handler: src/controller/translate/handler.translate
    events:
      - http:
          path: translate
          method: post
          authorizer: ${self:custom.authorizer}
  getSupportedLanguages:
    handler: src/controller/getSupportedLanguages/handler.getSupportedLanguages
    events:
      - http:
          path: supportedLanguages
          method: get
          authorizer: ${self:custom.authorizer}

plugins:
  - serverless-esbuild
  - serverless-offline
